name: "print_contexts"

inputs:
  github-context:
    description: "Github context"
    required: true
  env-context:
    description: "Env context"
    required: true
  vars-context:
    description: "Vars context"
    required: true
  job-context:
    description: "Job context"
    required: true
  steps-context:
    description: "Steps context"
    required: true
  runner-context:
    description: "Runner context"
    required: true
  secrets-context:
    description: "Secrets context"
    required: true
  strategy-context:
    description: "Strategy context"
    required: true
  matrix-context:
    description: "Matrix context"
    required: true
  needs-context:
    description: "Needs context"
    required: true
  inputs-context:
    description: "Inputs context"
    required: true

runs:
    using: "composite"
    steps:

      - name: Print github context
        shell: bash
        run: |
          echo "${{ inputs.github-context }}"
      
      - name: Print env context
        shell: bash
        run: |
          echo "${{ inputs.env-context }}"
      
      - name: Print vars context
        shell: bash
        run: |
          echo "${{ inputs.vars-context }}"

      - name: Print job context
        shell: bash
        run: |
          echo "${{ inputs.job-context }}"

      - name: Print steps context
        shell: bash
        run: |
          echo "${{ inputs.steps-context }}"

      - name: Print runner context
        shell: bash
        run: |
          echo "${{ inputs.runner-context }}"

      - name: Print secrets context
        shell: bash
        run: |
          echo "${{ inputs.secrets-context }}"

      - name: Print strategy context
        shell: bash
        run: |
          echo "${{ inputs.strategy-context }}"

      - name: Print matrix context
        shell: bash
        run: |
          echo "${{ inputs.matrix-context }}"

      - name: Print needs context
        shell: bash
        run: |
          echo "${{ inputs.needs-context }}"

      - name: Print inputs context
        shell: bash
        run: |
          echo "${{ inputs.inputs-context }}"
