name: "print_contexts"

inputs:
  format:
    description: "Format to print the data"
    required: false
    default: "json"
  json-indent:
    description: "Indentation for JSON output"
    required: false
    default: 2
  artifact:
    description: "Name of the artifact to upload. Leave unset for no artifact"
    required: false
  github:
    description: "Github context"
    required: true
  env:
    description: "Env context"
    required: true
  vars:
    description: "Vars context"
    required: true
  job:
    description: "Job context"
    required: true
  steps:
    description: "Steps context"
    required: true
  runner:
    description: "Runner context"
    required: true
  secrets:
    description: "Secrets context"
    required: true
  strategy:
    description: "Strategy context"
    required: true
  matrix:
    description: "Matrix context"
    required: true
  needs:
    description: "Needs context"
    required: true
  inputs:
    description: "Inputs context"
    required: true
    
runs:
    using: "node20"
    main: "dist/index.js"
