name: a

on: [push, pull_request]

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/print_contexts
