name: a

on: [push]

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: npm ci

      # - run: sleep 1m

      - name: version
        run: |
          npx nx release version
          rm -rf .nx/version-plans
          npm i

      - name: commit
        run: |
          git config --global user.email "goastler4@gmail.com"
          git config --global user.name "goastler"

          git diff --cached

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add .
          git commit -m "chore: release version"
          git push
