# name: release

# on:
#     workflow_dispatch:

# concurrency:
#     group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#     cancel-in-progress: false # queue the new runs until previous have finished. This avoids version bumps overlapping with each other

# defaults:
#     run:
#         shell: bash

# jobs:
#     release:
#         name: a
#         runs-on: ubuntu-latest
#         steps:
#             - name: Print contexts
#               uses: prosopo/captcha/.github/actions/print_contexts@gha
#               with:
#                     INPUTS_CONTEXT: ${{ toJson(inputs) }}
#                     NEEDS_CONTEXT: ${{ toJson(needs) }}
#                     VARS_CONTEXT: ${{ toJson(vars) }}
#                     SECRETS_CONTEXT: ${{ toJson(secrets) }}

                
#             - name: Export vars to env
#               run: |
#                 echo '${{ toJson(vars) }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV


#             - name: Print env
#               run: |
#                 echo "Environment variables:"
#                 env | sort
