name: a

on:
    pull_request:
        branches:
            - '*'

env:
    CARGO_TERM_COLOR: always
    GH_TOKEN: ${{ github.token }}

jobs:
    branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: nvm
              run: |
                nvm install
                nvm use
                nvm ls
