name: release

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: false # queue the new runs until previous have finished. This avoids version bumps overlapping with each other

defaults:
    run:
        shell: bash

jobs:
    release:
        name: a
        runs-on: ubuntu-latest
        steps:
            - name: Print contexts
              uses: prosopo/captcha/.github/actions/print_contexts@gha
              with:
                    INPUTS_CONTEXT: ${{ toJson(inputs) }}
                    NEEDS_CONTEXT: ${{ toJson(needs) }}
                    VARS_CONTEXT: ${{ toJson(vars) }}
                    SECRETS_CONTEXT: ${{ toJson(secrets) }}

            - name: a
              run: |
                VARS_JSON='${{ toJson(vars) }}'
                KEYS=$(echo "$VARS_JSON" | jq -r 'keys[]')
                for key in $KEYS; do
                  value=$(echo "$VARS_JSON" | jq -r --arg key "$key" '.[$key]')
                  echo "$key: $value"
                  echo "$key=$value" >> $GITHUB_ENV
                done

            - name: Print env
              run: |
                echo "Environment variables:"
                env | sort
