name: a

on:
    push:
        # only on the main branch
        branches:
            - main
    # or run manually
    workflow_dispatch:

# enqueues multiple jobs to run sequentially, not in parallel. This avoids race conditions related to version bumping
concurrency:
    group: ${{ github.workflow }}

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: abc
              run: echo "abc"
            - name: github context
              shell: bash
              run: echo "${{ toJson(github) }}"
            - name: env context
              shell: bash
              run: echo "${{ toJson(env) }}"
            - name: vars context
              shell: bash
              run: echo "${{ toJson(vars) }}"
            - name: job context
              shell: bash
              run: echo "${{ toJson(job) }}"
            - name: steps context
              shell: bash
              run: echo "${{ toJson(steps) }}"
            - name: runner context
              shell: bash
              run: echo "${{ toJson(runner) }}"
            - name: secrets context
              shell: bash
              run: echo "${{ toJson(secrets) }}"
            - name: strategy context
              shell: bash
              run: echo "${{ toJson(strategy) }}"
            - name: matrix context
              shell: bash
              run: echo "${{ toJson(matrix) }}"
            - name: needs context
              shell: bash
              run: echo "${{ toJson(needs) }}"
            - name: inputs context
              shell: bash
              run: echo "${{ toJson(inputs) }}"

            - uses: prosopo/captcha/.github/actions/print_vars@main