name: a

on: [push, pull_request]

env:
  A: 'a'
  B: 'b'
  C: 'c'

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: step1
        id: step1
        run: echo "Hello, world!"

      - uses: ./.github/actions/print_contexts
        with:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
          NEEDS_CONTEXT: ${{ toJson(needs) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - run: echo "${{ toJson(steps) }}"

      - uses: ./.github/actions/restore_npm_cache
