name: a

on:
  push:
    branches:
      - main

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: npm ci

      - run: sleep 2m

      - name: version
        run: |
          npx nx release version

      - name: remove version plans
        run: |
          rm -rfv .nx/version-plans

      - run: npm i

      - name: commit
        run: |
          git config --global user.email "goastler4@gmail.com"
          git config --global user.name "goastler"

          git add .

          git diff --cached

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: release version"
          git push

      - name: build
        run: |
          # HEAD is the latest commit and contains the version bumps
          npx nx show projects --affected --base ${{ github.event.before }} --head HEAD
