name: b

on:
  pull_request:
    branches:
      - main

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git diff --name-only --no-renames --relative "origin/main" "HEAD"

      - run: npm ci

      - name: check versions
        run: |
          npx nx release plan:check --verbose --base=${{ github.base_ref }} --head=${{ github.head_ref }}
