name: b

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: git fetch origin ${{ github.base_ref }}
      - run: git fetch origin ${{ github.head_ref }}

      - run: npm ci

      - name: check versions
        run: |
          npx @changesets/cli status --since="origin/${{ github.base_ref }}" --verbose
