name: b

on:
  pull_request:
    branches:
      - main

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show git status and branches
        run: |
          git status
          git branch -a

      - name: Fetch main branch explicitly
        run: |
          git fetch origin main

      - name: Show fetched branches
        run: |
          git branch -r

      - run: git diff --name-only --no-renames --relative "origin/main" "HEAD"

      - run: npm ci

      - name: check versions
        run: |
          npx nx release plan:check --verbose
