name: b

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Fetch main branch
        run: git fetch origin main

      - run: npm ci

      - name: check versions
        run: |
          npx @changesets/cli status --since="origin/${{ github.base_ref }}" --verbose
