name: b

on:
  pull_request:
    branches:
      - main

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npm ci

      - name: Fetch main branch
        run: git fetch origin main
        
      - run: git diff --name-only --no-renames --relative "main" "HEAD"

      - name: check versions
        run: |
          npx nx release plan:check --verbose
