name: blocky

on:
    issues:
        types:
            - opened
            - edited
            - closed
            - reopened
            - transferred
    issue_comment:
        types:
            - created
            - edited
            - deleted
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - edited
            - closed
            - labeled
            - unlabeled
    pull_request_comment:
        types:
            - created
            - edited
            - deleted
    pull_request_review_comment:
        types:
            - created
            - edited
            - deleted
    pull_request_review:
        types:
            - submitted
            - edited
            - dismissed


# TODO
# check if the PR is open or closed
#     if closed, remove the label
#     if open, add the label
# go through all linked issues/PRs and check if they are closed
#     if closed, remove the label and pass
#     if open, add the label and fail

jobs:
    blocky:
        runs-on: ubuntu-latest
        steps:
            - name: Configure labels
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # get the comments + body for the current PR
                  # search for linked issues/PRs (e.g. blocked by #xyz)
                  # check if the linked issues/PRs are closed
                  # if any are open, add the label and fail
                  # if all are closed, remove the label and pass
                  echo "trigger: ${{ github.event.action }}"

