name: bump

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  a:
    runs-on: ubuntu-latest
    steps:

      - name: git author
        run: |
        
          git config --global user.email "goastler4@gmail.com"
          git config --global user.name "goastler"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.KEY }}

      - run: git fetch origin ${{ github.event.before }}

      - run: npm ci

      - name: version
        run: |
        
          npx nx release version
          npm i

      - name: bump workspace
        run: |

          if git diff --quiet; then
            echo "No version changes"
            exit 0
          else
            echo "Changes detected, patching workspace"
            mkdir -p .nx/version-plans
            pkg=$(cat package.json | jq -r ".name")
            printf -- "---\n'$pkg': patch\n---\nworkspace member bumped\n" > .nx/version-plans/workspace-$(date +%s).json
            npx nx release version
            npm i
          fi

      - name: remove version plans
        run: |
        
          rm -rfv .nx/version-plans

      - name: commit
        run: |

          if git diff --quiet; then
            version=$(cat package.json | jq -r ".version")
            branchName="release/$version"
            git add .
            git checkout -b $branchName
            git commit -m "chore: release $version"
            git push origin $branchName
            echo pr to ${GITHUB_REF#refs/heads/}
            gh pr create --fill --base ${GITHUB_REF#refs/heads/}
          else
            echo "No version changes"
            exit 0
          fi

