name: bump

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  a:
    runs-on: ubuntu-latest
    steps:

      - name: git author
        run: |
        
          git config --global user.email "goastler4@gmail.com"
          git config --global user.name "goastler"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.KEY }}

      - run: git fetch origin ${{ github.event.before }}

      - run: npm ci

      - name: add workspace changeset
        run: |
          pkg=$(cat package.json | jq -r ".name")
          echo "---
'$pkg': patch
---

workspace member bumped
" > .nx/version-plans/workspace-$(date +%s).json"

      - name: version
        run: |
          npx nx release version
          npm i

      - name: remove version plans
        run: |
          rm -rfv .nx/version-plans

      - name: commit
        run: |

          version=$(cat package.json | jq -r ".version")
          branchName="release/$version"
          git checkout -b $branchName
          git add .

          if git diff --cached --quiet; then
            echo "No version changes"
            exit 0
          fi

          git commit -m "chore: release version"
          git push origin $branchName
          gh pr create --fill --base main
