name: c

on:
    push:
        branches:
            - main

jobs:
    c:
        runs-on: ubuntu-latest
        steps:
            - name: a
              run: |
                  echo "a"

                  diff=$(git show --pretty=format: --no-notes "${{ github.event.before }}..${{ github.event.after }}" -- package.json | cat)
                  echo "diff:"
                  echo "$diff"
                  echo ""
                