name: c

on:
    push:
        branches:
            - main

jobs:
    c:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: a
              run: |

                  diff=$(git show --pretty=format: --no-notes ${{ github.event.before }}..${{ github.event.after }} -- package.json | cat)
                  echo "diff:"
                  echo "$diff"
                  echo ""
                