name: c

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to release'
        required: true
      version:
        description: 'Version to release'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: fetch version from github packages
        run: |

          # login to the registry
          registry="npm.pkg.github.com"
          echo "//$registry/:_authToken=${{ secrets.GH_PAT }}" >> ~/.npmrc

          # Default registry for public packages
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

          # Custom registry for scoped packages
          echo "@${{ github.repository_owner }}:registry=https://$registry" >> ~/.npmrc

          # get the version from the package.json
          pkg="${{ github.event.inputs.package }}"
          version="${{ github.event.inputs.version }}"
          tag="$pkg@$version"
          npm pack $tag

          # unpack the tarball
          tar -xvzf *.tgz
          rm *.tgz
          cd package

          cat package.json | jq '.devDependencies | to_entries[] | "\(.key)@\(.value)"' | xargs -t npm i

          npm run deploy
