name: c

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to release'
        required: true
      version:
        description: 'Version to release'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: login to npm registry
        run: |
          # login to the registry
          registry="npm.pkg.github.com"
          echo "//$registry/:_authToken=${{ secrets.GH_PAT }}" >> ~/.npmrc

      - name: fetch version from github packages
        run: |
          # get the version from the package.json
          pkg="${{ github.event.inputs.package }}"
          version="${{ github.event.inputs.version }}"
          tag="$pkg@$version"
          npm pack $tag

          # unpack the tarball
          tar -xvzf *.tgz --strip-components=1
          rm *.tgz

      # install only the dev deps to allow deploy
      - run: npm i --only=dev

      - run: npm run deploy
