name: c

on:
    push:
        branches:
            - main

jobs:
    c:
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: a
              run: |
                  sleep 1m
                  echo x
                  diff=$(git show --pretty=format: --no-notes ${{ github.event.before }}..${{ github.event.after }} -- package.json | cat)
                  echo "diff:"
                  echo "$diff"
                  echo ""
                