name: c

on:
    push:
        branches:
            - main

jobs:
    c:
        runs-on: ubuntu-latest
        steps:
            - name: a
              run: |
                  echo "a"
                