name: d

on:
    workflow_dispatch:
    push:

jobs:
    d:
        runs-on: ubuntu-latest
        steps:
            - name: a
              run: |
                dpkg --get-selections | awk '{print $1}'
