name: d

on:
    workflow_dispatch:
    push:

jobs:
    d:
        runs-on: ubuntu-latest
        steps:
            - name: a
              run: |
                apt-mark showmanual
            - name: b
              run: |
                cat /etc/apt/sources.list
            - name: c
              run: |
                cat /etc/apt/sources.list.d/*.list
