name: d

on:
    workflow_dispatch:
    push:

jobs:
    d:
        runs-on: ubuntu-latest
        steps:

            - name: a
              run: |
                echo a
            - name: b
              run: |
                echo b
                exit 0
            - name: c
              run: |
                echo c
            
