name: d

on:
    workflow_dispatch:
    push:

jobs:
    
    a:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

        - name: Print contexts
          uses: ./.github/actions/print_contexts
          with:
            github: ${{ toJson(github) }}
            env: ${{ toJson(env) }}
            vars: ${{ toJson(vars) }}
            job: ${{ toJson(job) }}
            steps: ${{ toJson(steps) }}
            runner: ${{ toJson(runner) }}
            secrets: ${{ toJson(secrets) }}
            strategy: ${{ toJson(strategy) }}
            matrix: ${{ toJson(matrix) }}
            needs: ${{ toJson(needs) }}
            inputs: ${{ toJson(inputs) }}
        
        - run: ls -la
            
