name: d

on:
    workflow_dispatch:

jobs:
    d:
        runs-on: ubuntu-latest
        steps:
            - name: a
              run: |
                apt list --installed
            - name: b
              run: |
                dpkg --list
