name: d

on:
    workflow_dispatch:
    push:

jobs:
    a:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                environment: [dev, staging, prod]
        outputs:
            env: ${{ steps.detect_env.outputs.env }}
        steps:
            - name: detect env
              id: detect_env
              run: |
                echo a
                echo "env=${{ matrix.environment }}" >> "$GITHUB_OUTPUT"
    b:
        runs-on: ubuntu-latest
        needs: a
        steps:
            - name: a
              run: |
                echo a
                echo "The output from job1 is: ${{ needs.a.outputs.env }}"
            - name: b
              run: |
                echo b
            - name: c
              run: |
                echo c
            
