name: e

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: a
        with:
          github-token: ${{ secrets.PROSOPONATOR_PAT }}
          script: |
            const comment = context.payload.comment.body;
            // print the payload
            console.log(JSON.stringify(context.payload, null, 2));
            // split comment by space
            const words = comment.split(' ');
            // if first word is '@prosponator'
            if (words[0] === '@prosponator') {
              console.log('prosponator called');
              // if the next word is 'approve' then approve the pull request
                if (words[1] === 'approve') {
                    console.log('reacting');
                    // react to the comment with a thumbs up
                    github.reactions.createForIssueComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        comment_id: context.payload.comment.id,
                        content: 'rocket'
                    });
                    console.log('approving');
                    // approve the pull request
                    github.pulls.createReview({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.payload.issue.number,
                        event: 'APPROVE'
                    });
                } else {
                    console.log('unknown command');
                    console.log('reacting');
                    // react with confused
                    github.reactions.createForIssueComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        comment_id: context.payload.comment.id,
                        content: 'confused'
                    });
                }
            } else {
                console.log('prosponator not called')
            }