name: e

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            console.log(`Comment: ${comment}`);
            console.log(`PR: ${context.payload.issue.number}`);
            console.log(`Event: ${JSON.stringify(context.event, null, 2)}`);