name: e

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: a
        run: |
            echo A comment on PR $NUMBER
            echo event: ${{ toJson(github) }}

          