name: PR develop to main only

on:
  pull_request_target:
    types:
      - opened

jobs:
  build:
    name: PR develop to main only
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.ref_name != 'develop'
    steps:
      - name: exit
        run: exit 1