name: workflow1

on:
  push:
    branches:
      - xyz

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo hello
    - name: abc
      run: |
        set +e; gh extension install actions/gh-actions-cache; set -e
        REPO=${{ github.repository }}
        echo "$REPO"
        echo "Fetching list of cache key"
        # get all but the most recent cache
        cacheKeysForPR=$(gh actions-cache list --sort created-at --order desc --limit 100 -R $REPO --key docker_image_cache_${{ runner.os }}_${{ runner.arch }}-)
        echo caches to be removed:
        echo ${cacheKeysForPR}
