name: Reusable Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - name: a
        run: |
          sec="${{ secrets.ENV_SECRET_A }}"
          v="${{ vars.ENV_VAR_A }}"
          echo "environment: ${{ inputs.environment }}"
          echo "secret: $sec"
          echo "var: $v"
