name: xyz

on:
    # or run manually
    workflow_dispatch:
      inputs:
          version:
              type: string
              description: Version number (e.g. 1.2.3)
              required: true

jobs:
    xyz:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: a
              env:
                GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
              run: |
                # make a new branch for the version changes
                git switch -c bump-version-${{ github.event.inputs.version }}

                # set the author in git
                git config user.name "prosoponator[bot]"
                git config user.email "dev@prosopo.io"

                # commit the version changes
                echo $(date) > version.txt
                git add .
                git commit -m "Bump version to ${{ github.event.inputs.version }}"

                # push version changes
                git push --set-upstream origin bump-version-${{ github.event.inputs.version }}

                # create a PR for the release
                gh pr create --base main --title "Release ${{ github.event.inputs.version }}" --fill 2>&1
                