name: y

on:
  workflow_dispatch:
    inputs:
      target_env:
        type: string
        required: true
        default: staging

jobs:
  deploy:
    uses: ./.github/workflows/x.yml
    with:
      environment: ${{ github.event.inputs.target_env }}
